Doxygen research-training project: DialogueSystemScripts.XML_DialoguesDatabase Class Reference
DialogueSystemScripts.XML_DialoguesDatabase Class Reference
Класс для работы с базой данных диалогов на XML.
Public Member Functions
override DialogueSettings GetDialogueSettings (int dialogueID)
Метод для получения настроек диалога.
Private Member Functions
void Awake ()
void Init ()
List< DialogueSettings > TranslateItems (List< XML_DialogueSettings > dialoguesSettings)
List< AnswerSettings > TranslateAnswers (List< XML_AnswerSettings > answersSettings)
Private Attributes
TextAsset _xmlFile
List< DialogueSettings > _dialoguesSettings = new List<DialogueSettings>()
Detailed Description
Класс для работы с базой данных диалогов на XML.
Definition at line 12 of file XML_DialoguesDatabase.cs.
Member Function Documentation
Awake()
void DialogueSystemScripts.XML_DialoguesDatabase.Awake () private
Definition at line 39 of file XML_DialoguesDatabase.cs.
References DialogueSystemScripts.XML_DialoguesDatabase.Init().
         {
             Init();
         }
GetDialogueSettings()
override DialogueSettings DialogueSystemScripts.XML_DialoguesDatabase.GetDialogueSettings (int dialogueID) virtual
Метод для получения настроек диалога.
Parameters
dialogueID Идентификатор диалога. ID диалога в базе данных диалогов.
Returns
Настройки диалогового окна.
Примеры использования:
int dialogueSettingsID = 0;
DialogueSettings primarySettings;
DialogueSettings externalSettings = GetDialogueSettings(dialogueSettingsID);
primarySettings.Text = externalSettings.Text;
Implements DialogueSystemScripts.DialoguesDatabase.
Definition at line 33 of file XML_DialoguesDatabase.cs.
         {
             DialogueSettings result = _dialoguesSettings.Find(x => x.ID == dialogueID);
             return result;
         }
Init()
void DialogueSystemScripts.XML_DialoguesDatabase.Init () private
Definition at line 44 of file XML_DialoguesDatabase.cs.
References DialogueSystemScripts.XML_DialoguesDatabase.TranslateItems().
Referenced by DialogueSystemScripts.XML_DialoguesDatabase.Awake().
         {
             List<XML_DialogueSettings> xmlDialoguesSettings = new List<XML_DialogueSettings>();
             XmlSerializer serializer = new XmlSerializer(typeof(XML_DialoguesCollection));
             StringReader reader = new StringReader(_xmlFile.text);
             xmlDialoguesSettings.AddRange((serializer.Deserialize(reader) as XML_DialoguesCollection).Dialogues);
             reader.Close();
             _dialoguesSettings.AddRange(TranslateItems(xmlDialoguesSettings));
         }
TranslateAnswers()
List<AnswerSettings> DialogueSystemScripts.XML_DialoguesDatabase.TranslateAnswers (List< XML_AnswerSettings > answersSettings) private
Definition at line 76 of file XML_DialoguesDatabase.cs.
Referenced by DialogueSystemScripts.XML_DialoguesDatabase.TranslateItems().
         {
             List<AnswerSettings> translatedAnswerSettings = new List<AnswerSettings>();
             for (int j = 0; j < answersSettings.Count; j++)
             {
                 string text = answersSettings[j].Text;
                 AnswerSettings answerSettings = new AnswerSettings(text);
                 translatedAnswerSettings.Add(answerSettings);
             }
             return translatedAnswerSettings;
         }
TranslateItems()
List<DialogueSettings> DialogueSystemScripts.XML_DialoguesDatabase.TranslateItems (List< XML_DialogueSettings > dialoguesSettings) private
Definition at line 59 of file XML_DialoguesDatabase.cs.
References DialogueSystemScripts.XML_DialoguesDatabase.TranslateAnswers().
Referenced by DialogueSystemScripts.XML_DialoguesDatabase.Init().
         {
             List<DialogueSettings> translatedDialogueSettings = new List<DialogueSettings>();
             for (int i = 0; i < dialoguesSettings.Count; i++)
             {
                 string text = dialoguesSettings[i].Text;
                 int id = dialoguesSettings[i].ID;
                 DialogueSettings settings = new DialogueSettings(id, text);
                 translatedDialogueSettings.Add(settings);
                 translatedDialogueSettings[i].Answers.AddRange(TranslateAnswers(dialoguesSettings[i].Answers));
             }
             return translatedDialogueSettings;
         }
Member Data Documentation
_dialoguesSettings
List<DialogueSettings> DialogueSystemScripts.XML_DialoguesDatabase._dialoguesSettings = new List<DialogueSettings>() private
Definition at line 17 of file XML_DialoguesDatabase.cs.
_xmlFile
TextAsset DialogueSystemScripts.XML_DialoguesDatabase._xmlFile private
Definition at line 15 of file XML_DialoguesDatabase.cs.
The documentation for this class was generated from the following file:
source_for_doxygen/Task_Dialogues/Assets/Scripts/DialogueSystem/XML_DialoguesDatabase.cs