Doxygen research-training project: DialogueSystemScripts.DialogueSystem Class Reference
DialogueSystemScripts.DialogueSystem Class Reference
Класс, управляющий диалоговыми окнами.
Public Member Functions
void OpenNewDialogue (int dialogueID)
Метод, открывающий новое окно диалога.
void CloseCurrentDialogue ()
Метод, закрывающий текущее активное окно диалога.
void CloseAllDialogues ()
Метод, закрывающий все текущие открытые окна диалогов.
DialogueSettings GetDialogueSettings (int dialogueID)
Метод для получения настроек диалога.
Private Types
enum DataInputType { DataInputType.Direct, DataInputType.External }
Private Member Functions
void Start ()
void SubEvents ()
void UnsubEvents ()
void OnDestroy ()
void InitDialoguesSettings ()
void InitMainCanvasGroup ()
void InitDefaultRespawnPoint ()
void InitDatabase ()
void InitDialogueAnswers (List< AnswerSettings > answers, Dialogue dialogue)
void ApplyExternalData ()
void SetCurrentDialogueVisibility (bool value)
void MoveDialogueByActivity (bool value)
void RotateDialogueByActivity (bool value)
Dialogue CreateDialogue (DialogueSettings settings)
void CreateAnswer (AnswerSettings settings, Transform answersGroup)
void IncreaseOffset ()
void DecreaseOffset ()
void ResetOffset ()
void CheckForControllsBlock ()
Private Attributes
DataInputType _dataInputType
DialoguesDatabase _database
CanvasGroup _mainCanvasGroup
RectTransform _dialogueSpawnPoint
Dialogue _dialogueMainPrefab
Answer _answerMainPrefab
List< DialogueSettings > _dialoguesSettings
Vector3 _dialoguePositionOffset
Vector3 _dialoguePositionCurrentOffset
Vector3 _dialogueAngleOffset
Vector3 _dialogueAngleCurrentOffset
Stack< Dialogue > _dialogues = new Stack<Dialogue>()
Detailed Description
Класс, управляющий диалоговыми окнами.
Definition at line 10 of file DialogueSystem.cs.
Member Enumeration Documentation
DataInputType
enum DialogueSystemScripts.DialogueSystem.DataInputType strong private
Enumerator
Direct
External
Definition at line 12 of file DialogueSystem.cs.
 { Direct, External };
Member Function Documentation
ApplyExternalData()
void DialogueSystemScripts.DialogueSystem.ApplyExternalData () private
Definition at line 172 of file DialogueSystem.cs.
References DialogueSystemScripts.Models.DialogueSettings.Answers, DialogueSystemScripts.DialoguesDatabase.GetDialogueSettings(), and DialogueSystemScripts.Models.DialogueSettings.Text.
         {
             for (int i = 0; i < _dialoguesSettings.Count; i++)
             {
                 int dialogueSettingsID = _dialoguesSettings[i].ID;
                 DialogueSettings externalSettings = _database.GetDialogueSettings(dialogueSettingsID);
                 _dialoguesSettings[i].Text = externalSettings.Text;
                 for (int j = 0; j < externalSettings.Answers.Count; j++)
                 {
                     _dialoguesSettings[i].Answers[j].Text = externalSettings.Answers[j].Text;
                 }
             }
         }
CheckForControllsBlock()
void DialogueSystemScripts.DialogueSystem.CheckForControllsBlock () private
Definition at line 273 of file DialogueSystem.cs.
         {
             _mainCanvasGroup.interactable = !(_dialogues.Count > 0);
         }
CloseAllDialogues()
void DialogueSystemScripts.DialogueSystem.CloseAllDialogues ()
Метод, закрывающий все текущие открытые окна диалогов.
Definition at line 86 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.CloseCurrentDialogue().
         {
             while (_dialogues.Count > 0)
             {
                 CloseCurrentDialogue();
             }
         }
CloseCurrentDialogue()
void DialogueSystemScripts.DialogueSystem.CloseCurrentDialogue ()
Метод, закрывающий текущее активное окно диалога.
Definition at line 73 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.CheckForControllsBlock(), DialogueSystemScripts.DialogueSystem.DecreaseOffset(), and DialogueSystemScripts.DialogueSystem.SetCurrentDialogueVisibility().
         {
             Destroy(_dialogues.Pop().MainWindow);
             SetCurrentDialogueVisibility(true);
             CheckForControllsBlock();
             DecreaseOffset();
         }
CreateAnswer()
void DialogueSystemScripts.DialogueSystem.CreateAnswer (AnswerSettings settings, Transform answersGroup) private
Definition at line 239 of file DialogueSystem.cs.
References DialogueSystemScripts.Models.AnswerSettings.AnswerPrefab, and DialogueSystemScripts.Models.Answer.InitAnswer().
         {
             Answer answer = null;
             if (settings.AnswerPrefab != null)
             {
                 answer = Instantiate(settings.AnswerPrefab, answersGroup);
             }
             else
             {
                 answer = Instantiate(_answerMainPrefab, answersGroup);
             }
             answer.InitAnswer(settings);
         }
CreateDialogue()
Dialogue DialogueSystemScripts.DialogueSystem.CreateDialogue (DialogueSettings settings) private
Definition at line 222 of file DialogueSystem.cs.
References DialogueSystemScripts.Models.DialogueSettings.DialoguePrefab, and DialogueSystemScripts.Models.Dialogue.InitDialogue().
         {
             Dialogue dialogue;
             if (settings.DialoguePrefab != null)
             {
                 dialogue = Instantiate(settings.DialoguePrefab, _dialogueSpawnPoint, false);
             }
             else
             {
                 dialogue = Instantiate(_dialogueMainPrefab, _dialogueSpawnPoint, false);
             }
             dialogue.InitDialogue(settings);
             return dialogue;
         }
DecreaseOffset()
void DialogueSystemScripts.DialogueSystem.DecreaseOffset () private
Definition at line 261 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem._dialogueAngleOffset, and DialogueSystemScripts.DialogueSystem._dialoguePositionOffset.
         {
             _dialoguePositionCurrentOffset -= _dialoguePositionOffset;
             _dialogueAngleCurrentOffset -= _dialogueAngleOffset;
         }
GetDialogueSettings()
DialogueSettings DialogueSystemScripts.DialogueSystem.GetDialogueSettings (int dialogueID)
Метод для получения настроек диалога.
Parameters
dialogueID Идентификатор диалога. ID диалога в базе данных диалогов.
Returns
Настройки диалогового окна.
Примеры использования:
_dialogueSystem.GetDialogueSettings(_dialogueID).Answers[_answerID].IsActive = true;
Definition at line 105 of file DialogueSystem.cs.
         {
             return _dialoguesSettings.Find(x => x.ID == dialogueID);
         }
IncreaseOffset()
void DialogueSystemScripts.DialogueSystem.IncreaseOffset () private
Definition at line 255 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem._dialogueAngleOffset, and DialogueSystemScripts.DialogueSystem._dialoguePositionOffset.
         {
             _dialoguePositionCurrentOffset += _dialoguePositionOffset;
             _dialogueAngleCurrentOffset += _dialogueAngleOffset;
         }
InitDatabase()
void DialogueSystemScripts.DialogueSystem.InitDatabase () private
Definition at line 159 of file DialogueSystem.cs.
         {
             _database = FindObjectOfType<DialoguesDatabase>();
         }
InitDefaultRespawnPoint()
void DialogueSystemScripts.DialogueSystem.InitDefaultRespawnPoint () private
Definition at line 151 of file DialogueSystem.cs.
         {
             if (_dialogueSpawnPoint == null)
             {
                 _dialogueSpawnPoint = (RectTransform)_mainCanvasGroup.transform;
             }
         }
InitDialogueAnswers()
void DialogueSystemScripts.DialogueSystem.InitDialogueAnswers (List< AnswerSettings > answers, Dialogue dialogue) private
Definition at line 164 of file DialogueSystem.cs.
References DialogueSystemScripts.Models.Dialogue.AnswersGroup, and DialogueSystemScripts.DialogueSystem.CreateAnswer().
         {
             for (int j = 0; j < answers.Count; j++)
             {
                 CreateAnswer(answers[j], dialogue.AnswersGroup.transform);
             }
         }
InitDialoguesSettings()
void DialogueSystemScripts.DialogueSystem.InitDialoguesSettings () private
Definition at line 136 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.ApplyExternalData().
         {
             switch (_dataInputType)
             {
                 case DataInputType.External: ApplyExternalData(); break;
                 default: Debug.Log("Direct inputed data in use!"); break;
             }
         }
InitMainCanvasGroup()
void DialogueSystemScripts.DialogueSystem.InitMainCanvasGroup () private
Definition at line 145 of file DialogueSystem.cs.
         {
             _mainCanvasGroup = FindObjectOfType<CanvasGroup>();
             _mainCanvasGroup.blocksRaycasts = true;
         }
MoveDialogueByActivity()
void DialogueSystemScripts.DialogueSystem.MoveDialogueByActivity (bool value) private
Definition at line 198 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem._dialoguePositionCurrentOffset.
         {
             if (value)
             {
                 _dialogues.Peek().ResetTransformValues();
             }
             else
             {
                 _dialogues.Peek().transform.localPosition += _dialoguePositionCurrentOffset;
             }
         }
OnDestroy()
void DialogueSystemScripts.DialogueSystem.OnDestroy () private
Definition at line 131 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.UnsubEvents().
         {
             UnsubEvents();
         }
OpenNewDialogue()
void DialogueSystemScripts.DialogueSystem.OpenNewDialogue (int dialogueID)
Метод, открывающий новое окно диалога.
Parameters
dialogueID Идентификатор диалога, который необходимо открыть.
При открытии нового окна диалога предыдущее окно не закрывается!
Definition at line 53 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.CheckForControllsBlock(), DialogueSystemScripts.DialogueSystem.CreateDialogue(), DialogueSystemScripts.DialogueSystem.IncreaseOffset(), DialogueSystemScripts.DialogueSystem.InitDialogueAnswers(), and DialogueSystemScripts.DialogueSystem.SetCurrentDialogueVisibility().
         {
             if (dialogueID < _dialoguesSettings.Count)
             {
                 Dialogue dialogue = CreateDialogue(_dialoguesSettings[dialogueID]);
                 InitDialogueAnswers(_dialoguesSettings[dialogueID].Answers, dialogue);
                 SetCurrentDialogueVisibility(false);
                 _dialogues.Push(dialogue);
                 SetCurrentDialogueVisibility(true);
                 CheckForControllsBlock();
                 IncreaseOffset();
             }
         }
ResetOffset()
void DialogueSystemScripts.DialogueSystem.ResetOffset () private
Definition at line 267 of file DialogueSystem.cs.
         {
             _dialoguePositionCurrentOffset = new Vector3();
             _dialogueAngleCurrentOffset = new Vector3();
         }
RotateDialogueByActivity()
void DialogueSystemScripts.DialogueSystem.RotateDialogueByActivity (bool value) private
Definition at line 210 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem._dialogueAngleCurrentOffset.
         {
             if (value)
             {
                 _dialogues.Peek().ResetTransformValues();
             }
             else
             {
                 _dialogues.Peek().transform.localEulerAngles += _dialogueAngleCurrentOffset;
             }
         }
SetCurrentDialogueVisibility()
void DialogueSystemScripts.DialogueSystem.SetCurrentDialogueVisibility (bool value) private
Definition at line 187 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.MoveDialogueByActivity(), and DialogueSystemScripts.DialogueSystem.RotateDialogueByActivity().
         {
             if (_dialogues.Count > 0)
             {
                 _dialogues.Peek().IsDialogueActive = value;
                 MoveDialogueByActivity(value);
                 RotateDialogueByActivity(value);
             }
         }
Start()
void DialogueSystemScripts.DialogueSystem.Start () private
Definition at line 110 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.InitDatabase(), DialogueSystemScripts.DialogueSystem.InitDefaultRespawnPoint(), DialogueSystemScripts.DialogueSystem.InitDialoguesSettings(), DialogueSystemScripts.DialogueSystem.InitMainCanvasGroup(), and DialogueSystemScripts.DialogueSystem.SubEvents().
         {
             SubEvents();
             InitMainCanvasGroup();
             InitDefaultRespawnPoint();
             InitDatabase();
             InitDialoguesSettings();
         }
SubEvents()
void DialogueSystemScripts.DialogueSystem.SubEvents () private
Definition at line 121 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.CloseCurrentDialogue(), and DialogueSystemScripts.Models.Dialogue.OnDialogueClose.
         {
             Dialogue.OnDialogueClose += CloseCurrentDialogue;
         }
UnsubEvents()
void DialogueSystemScripts.DialogueSystem.UnsubEvents () private
Definition at line 126 of file DialogueSystem.cs.
References DialogueSystemScripts.DialogueSystem.CloseCurrentDialogue(), and DialogueSystemScripts.Models.Dialogue.OnDialogueClose.
         {
             Dialogue.OnDialogueClose -= CloseCurrentDialogue;
         }
Member Data Documentation
_answerMainPrefab
Answer DialogueSystemScripts.DialogueSystem._answerMainPrefab private
Definition at line 29 of file DialogueSystem.cs.
_database
DialoguesDatabase DialogueSystemScripts.DialogueSystem._database private
Definition at line 17 of file DialogueSystem.cs.
_dataInputType
DataInputType DialogueSystemScripts.DialogueSystem._dataInputType private
Definition at line 12 of file DialogueSystem.cs.
_dialogueAngleCurrentOffset
Vector3 DialogueSystemScripts.DialogueSystem._dialogueAngleCurrentOffset private
Definition at line 42 of file DialogueSystem.cs.
_dialogueAngleOffset
Vector3 DialogueSystemScripts.DialogueSystem._dialogueAngleOffset private
Definition at line 40 of file DialogueSystem.cs.
_dialogueMainPrefab
Dialogue DialogueSystemScripts.DialogueSystem._dialogueMainPrefab private
Definition at line 26 of file DialogueSystem.cs.
_dialoguePositionCurrentOffset
Vector3 DialogueSystemScripts.DialogueSystem._dialoguePositionCurrentOffset private
Definition at line 37 of file DialogueSystem.cs.
_dialoguePositionOffset
Vector3 DialogueSystemScripts.DialogueSystem._dialoguePositionOffset private
Definition at line 35 of file DialogueSystem.cs.
_dialogues
Stack<Dialogue> DialogueSystemScripts.DialogueSystem._dialogues = new Stack<Dialogue>() private
Definition at line 44 of file DialogueSystem.cs.
_dialogueSpawnPoint
RectTransform DialogueSystemScripts.DialogueSystem._dialogueSpawnPoint private
Definition at line 23 of file DialogueSystem.cs.
_dialoguesSettings
List<DialogueSettings> DialogueSystemScripts.DialogueSystem._dialoguesSettings private
Definition at line 32 of file DialogueSystem.cs.
_mainCanvasGroup
CanvasGroup DialogueSystemScripts.DialogueSystem._mainCanvasGroup private
Definition at line 20 of file DialogueSystem.cs.
The documentation for this class was generated from the following file:
Source for doxygen/Task_Dialogues/Assets/Scripts/DialogueSystem/DialogueSystem.cs